# Generated by Django 4.0.1 on 2022-01-24 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_documentuser'),
        ('project', '0002_alter_requestform_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('created_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('E', 'EVALUATION'), ('R', 'REJECTED'), ('A', 'APPROVED')], default='E', max_length=1)),
                ('special_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='user.specialuser')),
            ],
        ),
        migrations.CreateModel(
            name='MyInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('total_price', models.FloatField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_investment', to='project.investment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_investment', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='MyBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_bond', to='project.bond')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_bond', to='order.order')),
            ],
        ),
        migrations.CreateModel(
            name='MyAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('voucher', models.ImageField(blank=True, null=True, upload_to='image')),
                ('quantity', models.IntegerField()),
                ('sale_price', models.FloatField()),
                ('total_price', models.FloatField()),
                ('action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_action', to='project.action')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_action', to='order.order')),
            ],
        ),
    ]
