# Generated by Django 4.0.1 on 2022-01-24 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('special_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_user', to='user.specialuser')),
            ],
        ),
    ]
