# Generated by Django 4.0.1 on 2022-01-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_documentuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjuridic',
            name='special_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_juridic', to='user.specialuser'),
        ),
        migrations.AlterField(
            model_name='userjuridic',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_juridic', to=settings.AUTH_USER_MODEL),
        ),
    ]
