# Generated by Django 4.0.1 on 2022-01-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userjuridic',
            name='RUC',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='usernatural',
            name='DNI',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
