# Generated by Django 4.0.1 on 2022-01-26 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userjuridic_ruc_alter_usernatural_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernatural',
            name='special_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_natural', to='user.specialuser'),
        ),
    ]
