# Generated by Django 4.0.1 on 2022-01-28 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usernatural_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernatural',
            name='special_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_natural', to='user.specialuser'),
        ),
        migrations.AlterField(
            model_name='usernatural',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_natural', to=settings.AUTH_USER_MODEL),
        ),
    ]
